presubmits:
  cert-manager/policy-approver:

  - name: pull-cert-manager-policy-approver-verify
    context: pull-cert-manager-policy-approver-verify
    agent: kubernetes
    decorate: true
    always_run: true
    max_concurrency: 8
    annotations:
      testgrid-create-test-group: 'false'
    spec:
      containers:
      - image: golang:1.17
        args:
        - make
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi
