presubmits:
  jetstack/okta-kubectl-auth:
  - name: okta-kubectl-auth-quick-verify
    always_run: true
    skip_report: false
    context: okta-kubectl-auth-quick-verify
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: golang:1.11.4
        workingDir: /go/src/github.com/jetstack/okta-kubectl-auth
        command:
        - make
        - verify
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"
