presubmits:

  jetstack/testing:

  - name: pull-testing-verify-config
    always_run: true
    context: pull-testing-verify-config
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    spec:
      containers:
      - image: gcr.io/k8s-prow/checkconfig:v20190405-651ad49e6
        args:
        # TODO: make this not awful
        - /app/prow/cmd/checkconfig/app.binary.runfiles/io_k8s_test_infra/prow/cmd/checkconfig/linux_amd64_pure_stripped/app.binary
        - -strict=false
        - -warnings=mismatched-tide
        - -config-path=config/config.yaml
        - -job-config-path=config/jobs
        - -plugin-config=config/plugins.yaml
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
    trigger: "(?m)^/test config,?(\\s+|$)"
    rerun_command: "/test config"

  - name: pull-testing-verify-bazel
    always_run: true
    context: pull-testing-verify-bazel
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20190108-0a1da0a-0.21.0
        args:
        - runner
        - bazel
        - build
        - //...
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        securityContext:
          privileged: true
    trigger: "(?m)^/test verify,?(\\s+|$)"
    rerun_command: "/test verify"
