presubmits:

  jetstack/testing:

  - name: pull-testing-verify-config
    always_run: true
    context: pull-testing-verify-config
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20190108-0a1da0a-0.21.0
        args:
        - runner
        - bazel
        - test
        - //config/...
        - //hack/...
        - //prow/...
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        securityContext:
          privileged: true
    trigger: "(?m)^/test config,?(\\s+|$)"
    rerun_command: "/test config"

  - name: pull-testing-verify-images
    always_run: false
    context: pull-testing-verify-images
    run_if_changed: "^(images/|legacy/images/).*$"
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20190108-0a1da0a-0.21.0
        args:
        - runner
        - bazel
        - build
        - //images/...
        - //legacy/images/...
        resources:
          requests:
            cpu: 4
            memory: 12Gi
        securityContext:
          privileged: true
    trigger: "(?m)^/test images,?(\\s+|$)"
    rerun_command: "/test images"
