presubmits:

  jetstack/testing:
  - name: pull-testing-verify-config
    always_run: true
    context: pull-testing-verify-config
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20180831-a4c5a2b-0.16.1
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 4
            memory: 12Gi
        # TODO: investigate whether bazel requires privileged mode
        securityContext:
          privileged: true
    trigger: "(?m)^/test config,?(\\s+|$)"
    rerun_command: "/test config"
