presubmits:

  jetstack/testing:

  - name: pull-testing-verify-config
    always_run: true
    context: pull-testing-verify-config
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20180831-6c69576-0.16.1
        args:
        - bazel
        - test
        - //config/...
        - //hack/...
        - //prow/...
        resources:
          requests:
            cpu: 1
            memory: 2Gi
        securityContext:
          privileged: true
    trigger: "(?m)^/test config,?(\\s+|$)"
    rerun_command: "/test config"

  - name: pull-testing-verify-images
    always_run: true
    context: pull-testing-verify-images
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20180831-6c69576-0.16.1
        args:
        - runner
        - bazel
        - build
        - //images/...
        - //legacy/images/...
        resources:
          requests:
            cpu: 4
            memory: 12Gi
        securityContext:
          privileged: true
    trigger: "(?m)^/test images,?(\\s+|$)"
    rerun_command: "/test images"
