# minikube size job templates
.minikube_medium: &minikube_medium
  resources:
    requests:
      cpu: 3800m
      memory: 12Gi

presubmits:
  jetstack/navigator:

  - name: navigator-quick-verify
    always_run: true
    skip_report: false
    context: navigator-quick-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/gcloud-in-go:v20180831-6e6e29cs
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
    trigger: "(?m)^/test( all| verify| quick verify),?(\\s+|$)"
    rerun_command: "/test verify"

  - name: navigator-e2e-v1-7
    context: navigator-e2e-v1-7
    always_run: true
    trigger: "(?m)^/test( all| e2e( v?1.7)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.7"
    skip_report: false
    max_concurrency: 4
    agent: kubernetes
    labels:
      preset-service-account: "true"
      libvirt-socket: "true"
      minikube-support: "true"
      minikube-medium: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/libvirt: ""
      # Note: this is not supported yet by prow PodSpec, taint temporary removed
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.7.15
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        <<: *minikube_medium
        securityContext:
          privileged: true

  - name: navigator-e2e-v1-8
    context: navigator-e2e-v1-8
    always_run: true
    trigger: "(?m)^/test( all| e2e( v?1.8)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.8"
    skip_report: false
    max_concurrency: 4
    agent: kubernetes
    labels:
      preset-service-account: "true"
      libvirt-socket: "true"
      minikube-support: "true"
      minikube-medium: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/libvirt: ""
      # Note: this is not supported yet by prow PodSpec, taint temporary removed
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.8.10
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        <<: *minikube_medium
        securityContext:
          privileged: true

  - name: navigator-e2e-v1-9
    context: navigator-e2e-v1-9
    always_run: true
    trigger: "(?m)^/test( all| e2e( v?1.9)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.9"
    skip_report: false
    max_concurrency: 4
    agent: kubernetes
    labels:
      preset-service-account: "true"
      libvirt-socket: "true"
      minikube-support: "true"
      minikube-medium: "true"
    spec:
      nodeSelector:
        node-role.kubernetes.io/libvirt: ""
      # Note: this is not supported yet by prow PodSpec, taint temporary removed
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.9.6
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--clean"
        <<: *minikube_medium
        securityContext:
          privileged: true
