presubmits:
  cert-manager/istio-csr:

  - name: pull-cert-manager-istio-csr-verify
    agent: kubernetes
    decorate: true
    always_run: true
    max_concurrency: 8
    annotations:
      testgrid-create-test-group: 'false'
    branches:
    - ^main$
    spec:
      containers:
      - image: golang:1.16
        args:
        - make
        - verify
        resources:
          requests:
            cpu: 1
            memory: 1Gi

  - name: pull-cert-manager-istio-csr-ca-rotation
    context: pull-cert-manager-istio-csr-ca-rotation
    agent: kubernetes
    decorate: true
    always_run: true
    branches:
    - ^main$
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210927-4d1bd69-1.17
        args:
        - runner
        - make
        - carotation
        resources:
          requests:
            cpu: 3500m
            memory: 4Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.21, istio v1.7
  - name: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-7
    context: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-7
    # Match everything except PRs that only touch docs/
    always_run: true
    optional: false
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - ^main$
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210331-a8721c1-1.16
        args:
        - runner
        - make
        - e2e
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.21.1"
        - name: ISTIO_VERSION
          value: "1.7.6"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.21, istio v1.8
  - name: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-8
    context: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-8
    # Match everything except PRs that only touch docs/
    always_run: true
    optional: false
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - ^main$
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210331-a8721c1-1.16
        args:
        - runner
        - make
        - e2e
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.21.1"
        - name: ISTIO_VERSION
          value: "1.8.2"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.21, istio v1.9
  - name: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-9
    context: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-9
    # Match everything except PRs that only touch docs/
    always_run: true
    optional: false
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - ^main$
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210331-a8721c1-1.16
        args:
        - runner
        - make
        - e2e
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.21.1"
        - name: ISTIO_VERSION
          value: "1.9.1"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based istio-csr e2e job for Kubernetes v1.21, istio v1.10
  - name: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-10
    context: pull-cert-manager-istio-csr-k8s-v1-21-istio-v1-10
    # Match everything except PRs that only touch docs/
    always_run: true
    optional: false
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - ^main$
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/golang-dind:20210331-a8721c1-1.16
        args:
        - runner
        - make
        - e2e
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.21.1"
        - name: ISTIO_VERSION
          value: "1.10.0"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"
