postsubmits:
  jetstack/cert-manager:

  # Publish releases for v0.13.x
  - name: post-cert-manager-release-previous
    cluster: trusted
    branches:
    # Only run this job on v0.13.x tags
    - ^v?0\.13\.\d+(-(alpha|beta)\.\d+)?$
    always_run: true
    decorate: true
    labels:
      preset-dind-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cert-manager-publish-bot-credentials: "true"
      preset-chart-museum-deploy-credentials: "true"
      preset-deployer-github-token: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200305-35c2a27-1.0.0
        args:
        # Wrap the release script with the runner so we can use docker-in-docker
        - runner
        - bazel
        - run
        - //hack/release
        - --
        - --images
        - --chart
        - --manifests
        - --publish
        resources:
          requests:
            cpu: 1500m
            memory: 3Gi
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
