presubmits:
  jetstack/vault-unsealer:
  - name: vault-unsealer-quick-verify
    always_run: true
    skip_report: false
    context: vault-unsealer-quick-verify
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: golang:1.10.4
        workingDir: /go/src/github.com/jetstack/vault-unsealer
        command:
        - /bin/sh
        - -c
        - make -C puppet/modules/$(echo ${JOB_NAME} | awk -F- '{print $(NF-2)}') verify
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"
