presubmits:
  cert-manager/cert-manager:
  - name: pull-cert-manager-bazel-1.8
    always_run: true
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    # release-1.8 is tested via make, but there were still some leftover tests which were bazel-only
    # as of the release of 1.8, so we need to run bazel test for 1.8 too.
    # Still, the unit and integration tests _are_ running in make so we only need to run a subset of tests
    # here
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - bazel
        - test
        - --jobs=1
        - //hack/...
        resources:
          requests:
            cpu: 1
            memory: 2Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-deps
    always_run: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    # this test is not really valuable for release-1.8 since bazel isn't really used there
    # still, we might as well run it just in case
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - make
        - verify_deps
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # Helm chart verification currently requires Docker.
  # We maintain a standalone presubmit for running this.
  # See https://github.com/helm/chart-testing/issues/53
  - name: pull-cert-manager-chart-bazel
    always_run: true
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    annotations:
      testgrid-create-test-group: 'false'
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - make
        - verify_chart
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"

### E2E tests against all supported Kubernetes versions with all cert-manager alpha/beta feature gates enabled ###

  - name: pull-cert-manager-e2e-v1-19-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.19"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-20-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.20"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-21-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-enable-all-feature-gates-disable-ssa: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.21"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-22-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-enable-all-feature-gates: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.22"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-23-bazel
    always_run: true
    optional: false
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-enable-all-feature-gates: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.23"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

# The 1.24 e2e tests are specified in make and are in the generated tests

  - name: pull-cert-manager-e2e-feature-gates-disabled-23-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.23"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-feature-gates-disabled-22-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.22"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-feature-gates-disabled-21-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.21"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-feature-gates-disabled-20-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.20"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-feature-gates-disabled-19-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-disable-all-alpha-beta-feature-gates: "true"
      preset-cloudflare-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-skip-default: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.19"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"

#### E2E tests that are not included in the default test runs ###

  # An E2E test job to allow us to manually trigger the Venafi Cloud E2E tests
  # with the following GitHub comment:
  #
  #  /test pull-cert-manager-e2e-issuers-venafi-cloud-previous
  #
  # The regular presubmit jobs do not run Venafi Cloud e2e tests.
  #
  - name: pull-cert-manager-e2e-issuers-venafi-cloud-previous-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-focus-venafi-tpp: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.23"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"


  # An E2E test job to allow us to manually trigger the Venafi TPP E2E tests
  # with the following GitHub comment:
  #
  #  /test pull-cert-manager-e2e-issuers-venafi-tpp-previous
  #
  # The regular presubmit jobs do not run Venafi TPP e2e tests.
  #
  - name: pull-cert-manager-e2e-issuers-venafi-tpp-previous-bazel
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - release-1.8
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-venafi-cloud-credentials: "true"
      preset-retry-flakey-tests: "true"
      preset-ginkgo-focus-venafi-cloud: "true"
      preset-default-e2e-volumes: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20220512-b6ea825-4.2.1
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 3500m
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.23"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
      dnsConfig:
        options:
        - name: ndots
          value: "1"
