periodics:

- name: ci-cert-manager-release-0.12
  interval: 2h
  cluster: gke
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: release-0.12
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200121-1a8954b-1.0.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 6
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.16"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"
