# Plugin repository whitelist.
# Keys: Full repo name: "org/repo".
# Values: List of plugins to run against the repo.
---
triggers:
- repos:
  - jetstack/kube-lego
  - jetstack/test-infra
  - jetstack/navigator
  - jetstack/tarmak
  - jetstack/okta-kubectl-auth
  - jetstack/puppet-module-aws_ebs
  - jetstack/puppet-module-calico
  - jetstack/puppet-module-etcd
  - jetstack/puppet-module-kubernetes
  - jetstack/puppet-module-kubernetes_addons
  - jetstack/puppet-module-prometheus
  - jetstack/puppet-module-vault_client
  - jetstack/puppet-module-tarmak
  - jetstack/vault-helper
  - jetstack/vault-unsealer
  - jetstack/vault-plugin-auth-templated-aws
  trusted_org: jetstack
  only_org_members: true
- repos:
  - jetstack/cert-manager
  trusted_org: cert-manager
  only_org_members: true

blunderbuss:
  # Only request a review from 1 reviewer
  request_count: 1

external_plugins:
  jetstack:
  - name: needs-rebase
    events:
    - pull_request

# heart:
#   adorees:
#   - k8s-merge-robot

# slack:
#   mergewarnings:
#   - repos:
#     - kubernetes/kubernetes
#     channels:
#     - kubernetes-dev
#     whitelist:
#     - k8s-merge-robot

repo_milestone:
  # You can curl the following endpoint in order to determine the github ID of your team
  # responsible for maintaining the milestones:
  # curl -H "Authorization: token <token>" https://api.github.com/orgs/<org-name>/teams
  jetstack/cert-manager:
    # https://github.com/orgs/cert-manager/teams/milestone-maintainers
    maintainers_id: 2805308
    maintainers_team: milestone-maintainers

config_updater:
  maps:
    config/labels.yaml:
      name: label-config
    config/config.yaml:
      name: config
    config/plugins.yaml:
      name: plugins
    config/jobs/**/*.yaml:
      name: job-config

plugins:

  jetstack:
  - approve
  - assign
  - blockade
  - blunderbuss
  - cherry-pick-unapproved
  - dco
  - golint
  - heart
  - help
  - hold
  - label
  - lgtm
  - lifecycle
  - milestone
  - milestonestatus
  - override
  - owners-label
  - require-matching-label
  - shrug
  - size
  - skip
  - trigger
  - verify-owners
  - wip
  - yuks

  jetstack/cert-manager:
  - release-note

  jetstack/tarmak:
  - release-note

  jetstack/navigator:
  - release-note

  jetstack/testing:
  - config-updater

  munnerz/venafi-cm-demo:
  - trigger
