periodics:

- name: ci-flightdeck-staging-e2e
  interval: 1h
  cluster: trusted
  decorate: true
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: gcr.io/jetstack-workshops/portal-e2e@sha256:c91535714b0aa99b36222a5f2f6785e338e57f0786c8ddac2fe3b25938c3fc34
      args:
      - runner
      - python3
      - -m
      - pytest
      - tests/test_e2e.py
      env:
      - name: PORTAL_URL
        value: 'https://portal-staging.k8s.school'
      - name: SESSION
        valueFrom:
          secretKeyRef:
            name: flightdeck-staging-session-token
            key: session
      resources:
        requests:
          cpu: 1
          memory: 2Gi
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
