periodics:

- name: ci-flightdeck-staging-e2e
  interval: 1h
  spec:
    containers:
    - image: eu.gcr.io/jetstack-workshops/portal-e2e:canary
      imagePullPolicy: Always
      env:
      - name: PORTAL_URL
        value: 'https://portal-staging.k8s.school'
      - name: SESSION
        valueFrom:
          secretKeyRef:
            name: flightdeck-staging-session-token
            key: session
      resources:
        requests:
          cpu: 2900m
          memory: 2Gi
