.selenium_small: &selenium_small
  resources:
    requests:
      cpu: 2900m
      memory: 2Gi

periodics:

- name: ci-flightdeck-staging-e2e
  interval: 1h
  spec:
    containers:
    - image: gcr.io/jetstack-workshops/portal-e2e:canary
      imagePullPolicy: Always
      env:
      - name: PORTAL_URL
        value: 'https://portal-staging.k8s.school'
      - name: SESSION
        valueFrom:
          secretKeyRef:
            name: flightdeck-staging-session-token
            key: session
      <<: *selenium_small
