periodics:

- name: ci-flightdeck-production-e2e
  interval: 1h
  cluster: trusted
  decorate: true
  labels:
    preset-service-account: "true"
  spec:
    containers:
    - image: gcr.io/jetstack-workshops/portal-e2e@sha256:388a58c9f3e5ae8002591807abb5db7b22439c3e75d33c762bc397b3e59708eb
      args: ["python3", "-m", "pytest", "tests/test_e2e.py"]
      env:
      - name: PORTAL_URL
        value: 'https://flightdeck.jetstack.io'
      - name: SESSION
        valueFrom:
          secretKeyRef:
            name: flightdeck-production-session-token
            key: session
      resources:
        requests:
          cpu: 1
          memory: 2Gi
