presubmits:
  jetstack/kube-oidc-proxy:

  - name: pull-kube-oidc-proxy-verify
    always_run: true
    context: pull-kube-oidc-proxy-verify
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    spec:
      containers:
      - image: golang:1.12.1
        workingDir: /go/src/github.com/jetstack/kube-oidc-proxy
        args:
        - make
        - all
        resources:
          requests:
            cpu: 1
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-11
    context: pull-kube-oidc-proxy-e2e-v1-11
    # Match everything except PRs that only touch docs/
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20190213-5eafc6f-0.21.0
        workingDir: /go/src/github.com/jetstack/kube-oidc-proxy
        args:
        - make
        - e2e
        resources:
          requests:
            cpu: 2
            memory: 6Gi
        env:
        - name: KIND_IMAGE
          value: eu.gcr.io/jetstack-build-infra-images/kind:1.11.8-1
        - name: K8S_VERSION
          value: "1.11"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
    trigger: "(?m)^/test( e2e( v?1.11)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.11"

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-12
    context: pull-kube-oidc-proxy-e2e-v1-12
    # Match everything except PRs that only touch docs/
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20190213-5eafc6f-0.21.0
        workingDir: /go/src/github.com/jetstack/kube-oidc-proxy
        args:
        - make
        - e2e
        resources:
          requests:
            cpu: 2
            memory: 6Gi
        env:
        - name: KIND_IMAGE
          value: eu.gcr.io/jetstack-build-infra-images/kind:1.12.6-1
        - name: K8S_VERSION
          value: "1.12"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
    trigger: "(?m)^/test( e2e( v?1.12)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.12"

  # kind based kube-oidc-proxy e2e job
  - name: pull-kube-oidc-proxy-e2e-v1-13
    context: pull-kube-oidc-proxy-e2e-v1-13
    # Match everything except PRs that only touch docs/
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    labels:
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20190213-5eafc6f-0.21.0
        workingDir: /go/src/github.com/jetstack/kube-oidc-proxy
        args:
        - make
        - e2e
        resources:
          requests:
            cpu: 2
            memory: 6Gi
        env:
        - name: KIND_IMAGE
          value: eu.gcr.io/jetstack-build-infra-images/kind:1.13.4-1
        - name: K8S_VERSION
          value: "1.13"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
    trigger: "(?m)^/test( e2e( v?1.13)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.13"
