periodics:

- name: cert-manager-website-update-index
  cluster: trusted
  interval: 12h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: cert-manager
    repo: website
    base_ref: master
  labels:
    preset-service-account: "true"
  annotations:
    testgrid-dashboards: jetstack-cert-manager-website
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    testgrid-disable-prowjob-analysis: "true"
    description: Updates the algolia search index for the cert-manager website
  spec:
    containers:
    - image: "eu.gcr.io/jetstack-build-infra-images/golang-nodejs:20210923-fe8699b-1.16.6"
      args:
      - bash
      - scripts/index
      env:
      - name: ALGOLIA_WRITE_KEY
        valueFrom:
          secretKeyRef:
            name: cert-manager-website-algolia-key
            key: ALGOLIA_WRITE_KEY
      resources:
        requests:
          cpu: 1
          memory: 2Gi
    dnsConfig:
      options:
        - name: ndots
          value: "1"
