presubmits:
  jetstack/terraform-google-gke-cluster:
  - name: pull-terraform-google-gke-cluster-verify
    context: pull-terraform-google-gke-cluster-verify
    always_run: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    annotations:
      testgrid-create-test-group: 'false'
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/terraform-google-gke-cluster:20190722-34eca10
        args:
        - ./hack/verify.sh
        resources:
          requests:
            cpu: 1
            memory: 2Gi
    trigger: "(?m)^/test verify( \\[.+\\])?$"
    rerun_command: "/test verify"
