name: bazel-tools # Name of the image to be built

variants:
  "10.24":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/golang-dind@sha256:bf41f2a8f6191842ad3ff56a071448ed6a8bdcece4d6d62c5d91733c2f1f3541"
      NODE_VERSION: "10.24.0~dfsg-1~deb10u1"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${NODE_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${NODE_VERSION}
