name: bazel-tools # Name of the image to be built

variants:
  "10.24":
    arguments:
      BASE_IMAGE: "eu.gcr.io/jetstack-build-infra-images/golang-dind@sha256:a71c5e6e8cb6875e9f6a43b722254693759b5db77566e25ba9eb52ca74b92e08"
      # Version of Bazel that is bundled in the BASE_IMAGE
      BAZEL_VERSION: "4.2.1"
      # Version of Go that is bundled in the BASE_IMAGE
      GO_VERSION: "1.17"
      NODE_VERSION: "10.24.0~dfsg-1~deb10u1"
      # This DOCKER_TAG is the Docker tag that corresponds to the Node version
      # we use. We don't use the Node version directly because it is not a valid
      # Docker tag.
      NODE_DOCKER_TAG: "10.24.0"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${DOCKER_TAG}
- ${_REGISTRY}/${_NAME}:bazel${BAZEL_VERSION}-go${GO_VERSION}-node${NODE_DOCKER_TAG}
