name: golang-dind # Name of the image to be built

variants:
  "1.13.4":
    arguments:
      BASE_IMAGE: "${_REGISTRY}/bazelbuild:20191016-eff358a-1.0.0"
      GO_VERSION: "1.13.4"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${GO_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${GO_VERSION}
