name: golang-dind # Name of the image to be built

variants:
  "1.13.4":
    arguments:
      GO_VERSION: "1.13.4"
      BAZEL_VERSION: "1.0.0"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${GO_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${GO_VERSION}
