apiVersion: apps/v1
kind: Deployment
metadata:
  name: triageparty
  namespace: triageparty
spec:
  selector:
    matchLabels:
      app: triageparty
  template:
    metadata:
      labels:
        app: triageparty
    spec:
      containers:
      - name: triageparty
        image: triageparty/triage-party:1.4.0
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: triageparty-github-token
              key: token
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        configMap:
          name: triageparty-config
