presubmits:
  jetstack/vault-plugin-auth-templated-aws:
  - name: vault-plugin-auth-templated-aws-quick-verify
    always_run: true
    skip_report: false
    context: vault-plugin-auth-templated-aws-quick-verify
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: golang:1.11.4
        workingDir: /go/src/github.com/jetstack/vault-plugin-auth-templated-aws
        command:
        - make
        - all
        resources:
          requests:
            cpu: 750m
            memory: 1Gi
    trigger: "(?m)^/test( all| verify|)( \\[.+\\])?$"
    rerun_command: "/test verify"
