periodics:

- name: ci-cert-manager-bazel
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    description: Runs 'bazel test --jobs=1 //...'
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - bazel
      - test
      - --jobs=1
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
        - name: ndots
          value: "1"

- name: ci-cert-manager-bazel-experimental
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs 'bazel test --jobs=1 //...' using the 'experimental' Bazel version
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210331-363c37a-experimental
      args:
      - runner
      - bazel
      - test
      - --jobs=1
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
        - name: ndots
          value: "1"

# kind based cert-manager e2e job
- name: ci-cert-manager-e2e-v1-16
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.16"
      # Disable CertificateSigningRequest e2e tests for pre v1.19 clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=false"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
        - name: ndots
          value: "1"

- name: ci-cert-manager-e2e-v1-17
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.17"
      # Disable CertificateSigningRequest e2e tests for pre v1.19 clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=false"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-18
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.18 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.18"
      # Disable CertificateSigningRequest e2e tests for pre v1.19 clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=false"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-19
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.19 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.19"
      # Enable CertificateSigningRequest and Gateway API e2e tests for v1.19+ clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=true,ExperimentalGatewayAPISupport=true"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-20
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.20"
      # Enable CertificateSigningRequest and Gateway API e2e tests for v1.19+ clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=true,ExperimentalGatewayAPISupport=true"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-21
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.21 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.21"
      # Enable CertificateSigningRequest and Gateway API e2e tests for v1.19+ clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=true,ExperimentalGatewayAPISupport=true"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-22
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.22 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.22"
      # Enable CertificateSigningRequest and Gateway API e2e tests for v1.19+ clusters
      - name: FEATURE_GATES
        value: "ExperimentalCertificateSigningRequestControllers=true,ExperimentalGatewayAPISupport=true"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"


- name: ci-cert-manager-upgrade
  interval: 8h
  agent: kubernetes
  decorate: true
  # extra refs specify what repo should be cloned
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs cert-manager upgrade test every 8 hours
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - make
      - cluster
      - verify_upgrade
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.22"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: aws-tests
  interval: 48h
  agent: kubernetes
  decorate: true
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a EKS cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-aws-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/golang-aws@sha256:1f330e4c9552ca383d157067b73fb0e090b64b0777939fd59e58b60e06020d66
      args:
      - bash 
      - -c
      - |
        set -euo && \
        git clone https://github.com/jetstack/cert-manager.git && \
        git clone https://github.com/cert-manager/test-infra.git && \
        cd test-infra/aws && \
        terraform init && \
        trap 'terraform destroy -auto-approve' ERR && \
        terraform apply -auto-approve && \
        ls && \
        pwd && \
        cd .. && \
        cd .. && \
        cd cert-manager && \
        ./devel/run-e2e.sh --ginkgo.focus "Public ACME Server HTTP01 Issuer" --acme-server-url=https://acme-staging-v02.api.letsencrypt.org/directory --ingress-controller-domain=aws.e2e-tests.cert-manager.io --testing-acme-email=cert-manager-dev-alerts@googlegroups.com --kubernetes-config=/home/prow/go/src/github.com/jetstack/cert-manager/test-infra/aws/kubeconfig_cert-manager-cluster || true && \
        cd /home/prow/go/src/github.com/jetstack/cert-manager/test-infra/aws && \
        terraform destroy -auto-approve;
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
