periodics:

- name: ci-cert-manager-bazel
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    description: Runs 'bazel test //...'
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
        - name: ndots
          value: "1"

- name: ci-cert-manager-bazel-experimental
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs 'bazel test //...' using the 'experimental' Bazel version
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210331-363c37a-experimental
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
        - name: ndots
          value: "1"

# kind based cert-manager e2e job
- name: ci-cert-manager-e2e-v1-16
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.16"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
        - name: ndots
          value: "1"

- name: ci-cert-manager-e2e-v1-17
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.17"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-18
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.18 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.18"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-19
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.19 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.19"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-20
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-venafi-cloud-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210323-ad5071a-3.7.2
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.20"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: eks-http01-tests
    always_run: false
    optional: true
    spec:
      containers:
      - image: hashicorp/terraform
        command:
        - /bin/bash
        args:
        - -c
        - |
          set -euo; \
          git clone https://github.com/jetstack/cert-manager; \
          git clone https://github.com/cert-manager/test-infra.git; \
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; \
          unzip awscliv2.zip; \
          sudo ./aws/install; \
          aws --version; \
          curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator; \
          chmod +x ./aws-iam-authenticator; \
          mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin; \
          echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc; \
          aws-iam-authenticator help; \
          cd test-infra/aws; \
          terraform init; \
          terraform apply -auto-approve; \
          cd..; \
          cd..; \
          go get github.com/onsi/ginkgo/ginkgo; \
          go get github.com/onsi/gomega/...; \
          cd cert-manager; \
          bazel build //test/e2e:e2e.test; \
          ginkgo -focus 'HTTP01' -skip '(External Account Binding|1 hour validity|IP Address|IP and DNS)' -nodes 10 -flakeAttempts 1 $(bazel info bazel-genfiles)/test/e2e/e2e.test -- --repo-root=$(pwd) --acme-server-url=https://acme-staging-v02.api.letsencrypt.org/directory --ingress-controller-domain=aws.e2e-tests.cert-manager.io --testing-acme-email=arshsharma461+acme-tests-1@gmail.com --kubernetes-config=/home/arsh/projects/forks/test-infra-1/aws/kubeconfig_cert-manager-cluster;
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-master
      description: Runs the end-to-end test suite against a EKS cluster
