.minikube_small: &minikube_small
  resources:
    requests:
      cpu: 2900m
      memory: 8Gi

presubmits:
  jetstack/cert-manager:

  # bazel based cert-manager verify test
  # TODO: port to jetstack/testing images
  - name: pull-cert-manager-bazel
    always_run: false
    skip_report: false
    context: pull-cert-manager-bazel
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20180901-b2e416b-0.16.1
        args:
        - runner
        - hack/verify-all.sh
        - //... # additional test targets
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        env:
        - name: GOPATH
          value: "/go"
        securityContext:
          privileged: true
    trigger: "(?m)^/test bazel,?(\\s+|$)"
    rerun_command: "/test bazel"
