periodics:

- name: ci-cert-manager-bazel
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    description: Runs 'bazel test --jobs=1 //...'
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - bazel
      - test
      - --jobs=1
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
    dnsConfig:
      options:
        - name: ndots
          value: "1"

# Re-add bazel-experimental periodics once Bazel v5.0.0 is released and we have
# a bazelbuild image with that https://github.com/bazelbuild/bazel/releases

# kind based cert-manager e2e job
- name: ci-cert-manager-e2e-v1-16
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-disable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.16"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
        - name: ndots
          value: "1"

- name: ci-cert-manager-e2e-v1-17
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-disable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.17"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-18
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.18 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-disable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.18"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-19
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.19 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-enable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.19"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-20
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.20 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-enable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.20"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-21
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.21 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-enable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.21"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: ci-cert-manager-e2e-v1-22
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a Kubernetes v1.22 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
    preset-enable-all-feature-gates: "true"
    preset-ginkgo-skip-default: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.22"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

# This test runs Venafi Cloud tests once every 24hrs.
# This is the only CI test job that runs those.
- name: ci-cert-manager-venafi-cloud
  interval: 24h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs Venafi Cloud e2e tests against Kubernetes v1.22 cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-venafi-cloud-credentials: "true"
    preset-ginkgo-focus-venafi-cloud: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - devel/ci-run-e2e.sh
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.22"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"


- name: ci-cert-manager-upgrade
  interval: 8h
  agent: kubernetes
  decorate: true
  # extra refs specify what repo should be cloned
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs cert-manager upgrade test every 8 hours
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20210831-4cf7b0b-4.2.1
      args:
      - runner
      - make
      - cluster
      - verify_upgrade
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
      env:
      - name: K8S_VERSION
        value: "1.22"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
    dnsConfig:
      options:
      - name: ndots
        value: "1"

- name: aws-tests
  interval: 48h
  agent: kubernetes
  decorate: true
  extra_refs:            # Periodic job doesn't clone any repo by default, needs to be added explicitly
    - org: cert-manager
      repo: test-infra
      base_ref: main
    - org: jetstack
      repo: cert-manager
      base_ref: master
  annotations:
    testgrid-create-test-group: 'true'
    testgrid-dashboards: jetstack-cert-manager-master
    testgrid-alert-email: cert-manager-dev-alerts@googlegroups.com
    description: Runs the end-to-end test suite against a EKS cluster
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-aws-credentials: "true"
    preset-ginkgo-focus-http01-ingress: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/golang-aws@sha256:1f330e4c9552ca383d157067b73fb0e090b64b0777939fd59e58b60e06020d66
      args:
      - bash 
      - -c
      - |
        set -euo && \
        ls && \
        pwd && \
        cd /home/prow/go/src/github.com/cert-manager/test-infra/aws && \
        terraform init && \
        trap 'terraform destroy -auto-approve' ERR && \
        terraform apply -auto-approve && \
        ls && \
        pwd && \
        cd /home && \
        ls && \
        cd /home/prow/go/src/github.com/jetstack/cert-manager && \
        ./devel/run-e2e.sh --acme-server-url=https://acme-staging-v02.api.letsencrypt.org/directory --ingress-controller-domain=aws.e2e-tests.cert-manager.io --testing-acme-email=cert-manager-dev-alerts@googlegroups.com --kubernetes-config=/home/prow/go/src/github.com/cert-manager/test-infra/aws/kubeconfig_cert-manager-cluster || true && \
        cd /home/prow/go/src/github.com/cert-manager/test-infra/aws && \
        terraform destroy -auto-approve;
      resources:
        requests:
          cpu: 3500m
          memory: 12Gi
