periodics:

- name: ci-cert-manager-bazel
  interval: 2h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20181107-8aac55d-0.18.0
      args:
      - runner
      - bazel
      - test
      - //...
      resources:
        requests:
          cpu: 2
          memory: 4Gi
  trigger: "(?m)^/test verify,?(\\s+|$)"
  rerun_command: "/test verify"

# kind based cert-manager e2e job
- name: ci-cert-manager-e2e-v1-11
  interval: 4h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20181107-8aac55d-0.18.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      # TODO: remove this after https://github.com/jetstack/cert-manager/pull/1215 merges
      - name: KIND_IMAGE
        value: eu.gcr.io/jetstack-build-infra-images/kind:1.11.4-1
      # The Bazel target used to build the kind cluster
      - name: KIND_TARGET
        value: //test/e2e:e2e-1.11
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory

- name: ci-cert-manager-e2e-v1-12
  interval: 4h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20181107-8aac55d-0.18.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      # TODO: remove this after https://github.com/jetstack/cert-manager/pull/1215 merges
      - name: KIND_IMAGE
        value: eu.gcr.io/jetstack-build-infra-images/kind:1.12.2-1
      # The Bazel target used to build the kind cluster
      - name: KIND_TARGET
        value: //test/e2e:e2e-1.12
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory

- name: ci-cert-manager-e2e-v1-13
  interval: 4h
  agent: kubernetes
  decorate: true
  extra_refs:
  - org: jetstack
    repo: cert-manager
    base_ref: master
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    preset-cloudflare-credentials: "true"
    preset-venafi-tpp-credentials: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20181107-8aac55d-0.18.0
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      # TODO: remove this after https://github.com/jetstack/cert-manager/pull/1215 merges
      - name: KIND_IMAGE
        value: kindest/node:v1.13.2
      # The Bazel target used to build the kind cluster
      - name: KIND_TARGET
        value: //test/e2e:e2e-1.13
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
