.minikube_small: &minikube_small
  resources:
    requests:
      cpu: 2900m
      memory: 8Gi

presubmits:
  jetstack/cert-manager:

  # bazel based cert-manager verify test
  # TODO: port to jetstack/testing images
  - name: pull-cert-manager-bazel
    always_run: false
    skip_report: false
    context: pull-cert-manager-bazel
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20180901-b2e416b-0.16.1
        args:
        - runner
        - hack/verify-all.sh
        - //... # additional test targets
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        env:
        - name: GOPATH
          value: "/go"
        securityContext:
          privileged: true
    trigger: "(?m)^/test bazel,?(\\s+|$)"
    rerun_command: "/test bazel"

  # kind based cert-manager e2e job
  - name: pull-cert-manager-e2e-v1-11
    always_run: false
    skip_report: false
    context: pull-cert-manager-e2e-v1-11
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/cert-manager-e2e:v20180907-14386ae-0.16.1
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 2
            memory: 6Gi
        env:
        - name: KIND_IMAGE
          value: eu.gcr.io/jetstack-build-infra-images/kind:1.11.2-0
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
    trigger: "(?m)^/test( e2e( v?1.11)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.11"

  - name: pull-cert-manager-e2e-v1-10
    always_run: false
    skip_report: false
    context: pull-cert-manager-e2e-v1-10
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/cert-manager-e2e:v20180907-14386ae-0.16.1
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 2
            memory: 6Gi
        env:
        - name: KIND_IMAGE
          value: eu.gcr.io/jetstack-build-infra-images/kind:1.10.7-0
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
    trigger: "(?m)^/test( e2e( v?1.10)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.10"

  - name: pull-cert-manager-e2e-v1-9
    always_run: false
    skip_report: false
    context: pull-cert-manager-e2e-v1-9
    max_concurrency: 2
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/cert-manager-e2e:v20180907-14386ae-0.16.1
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 2
            memory: 6Gi
        env:
        - name: KIND_IMAGE
          value: eu.gcr.io/jetstack-build-infra-images/kind:1.9.10-0
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
    trigger: "(?m)^/test( e2e( v?1.9)?|)( \\[.+\\])?$"
    rerun_command: "/test e2e v1.9"
