presets:
- labels:
    preset-cloudflare-credentials: "true"
  env:
  - name: CLOUDFLARE_E2E_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: api-token
  - name: CLOUDFLARE_E2E_EMAIL
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: email
  - name: CLOUDFLARE_E2E_DOMAIN
    valueFrom:
      secretKeyRef:
        name: cloudflare-api-key
        key: domain

- labels:
    preset-venafi-tpp-credentials: "true"
  env:
  - name: VENAFI_TPP_URL
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: url
  - name: VENAFI_TPP_ZONE
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: zone
  - name: VENAFI_TPP_USERNAME
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: username
  - name: VENAFI_TPP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: venafi-tpp
        key: password

- labels:
    preset-retry-flakey-tests: "true"
  env:
  - name: FLAKE_ATTEMPTS
    value: "2"

presubmits:
  jetstack/cert-manager:

  - name: pull-cert-manager-bazel
    always_run: true
    cluster: gke
    context: pull-cert-manager-bazel
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs 'bazel test //...'
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-bazel-experimental
    always_run: false
    optional: true
    cluster: gke
    context: pull-cert-manager-bazel-experimental
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs 'bazel test //...' using the 'experimental' Bazel version
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-experimental
        args:
        - runner
        - bazel
        - test
        - //...
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # Helm chart verification currently requires Docker.
  # We maintain a standalone presubmit for running this.
  # See https://github.com/helm/chart-testing/issues/53
  - name: pull-cert-manager-chart
    always_run: true
    cluster: gke
    context: pull-cert-manager-chart
    max_concurrency: 8
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Verifies the Helm chart passes linting checks
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - make
        - verify_chart
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        # docker-in-docker needs privileged mode
        securityContext:
          privileged: true
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-deps
    always_run: true
    cluster: gke
    context: pull-cert-manager-deps
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Verifies dependency related files are up to date
    labels:
      preset-service-account: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - make
        - verify_deps
        resources:
          requests:
            cpu: 2
            memory: 4Gi
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  # kind based cert-manager e2e job
  - name: pull-cert-manager-e2e-v1-11
    cluster: gke
    context: pull-cert-manager-e2e-v1-11
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.11 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.11"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"

  - name: pull-cert-manager-e2e-v1-12
    cluster: gke
    context: pull-cert-manager-e2e-v1-12
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.12 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.12"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-e2e-v1-13
    cluster: gke
    context: pull-cert-manager-e2e-v1-13
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.13 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.13"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-e2e-v1-14
    cluster: gke
    context: pull-cert-manager-e2e-v1-14
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.14 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.14"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-e2e-v1-15
    cluster: gke
    context: pull-cert-manager-e2e-v1-15
    always_run: false
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.15 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.15"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-e2e-v1-16
    cluster: gke
    context: pull-cert-manager-e2e-v1-16
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.16 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.16"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"

  - name: pull-cert-manager-e2e-v1-17
    cluster: gke
    context: pull-cert-manager-e2e-v1-17
    always_run: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    annotations:
      testgrid-create-test-group: 'true'
      testgrid-dashboards: jetstack-cert-manager-presubmits-blocking
      description: Runs the end-to-end test suite against a Kubernetes v1.17 cluster
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200310-84c402b-2.2.0
        args:
        - runner
        - hack/ci/run-e2e-kind.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: K8S_VERSION
          value: "1.17"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
        - name: ndots
          value: "1"
# OpenShift e2e tests
  - name: pull-cert-manager-e2e-openshift-v3-11
    cluster: gke
    context: pull-cert-manager-e2e-openshift-v3-11
    always_run: false
    optional: true
    max_concurrency: 4
    agent: kubernetes
    decorate: true
    branches:
    - master
    - release-0.15
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
      preset-bazel-remote-cache-enabled: "true"
      preset-bazel-scratch-dir: "true"
      preset-cloudflare-credentials: "true"
      preset-venafi-tpp-credentials: "true"
      preset-retry-flakey-tests: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:20200121-1a8954b-1.0.0
        args:
        - runner
        - devel/ci-run-e2e.sh
        resources:
          requests:
            cpu: 6
            memory: 12Gi
        env:
        - name: OPENSHIFT_VERSION
          value: "3.11"
        - name: IS_OPENSHIFT
          value: "true"
        securityContext:
          privileged: true
          capabilities:
            add: ["SYS_ADMIN"]
        volumeMounts:
        - mountPath: /lib/modules
          name: modules
          readOnly: true
        - mountPath: /sys/fs/cgroup
          name: cgroup
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
          type: Directory
      dnsConfig:
        options:
          - name: ndots
            value: "1"
