.minikube_small: &minikube_small
  resources:
    requests:
      cpu: 2900m
      memory: 8Gi

periodics:

- name: ci-cert-manager-e2e-v1-7
  interval: 12h
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.7.15
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      env:
      - name: DISABLE_WEBHOOK
        value: "true"
      <<: *minikube_small
      securityContext:
        privileged: true

- name: ci-cert-manager-e2e-v1-8
  interval: 12h
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.8.10
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      env:
      - name: DISABLE_WEBHOOK
        value: "true"
      <<: *minikube_small
      securityContext:
        privileged: true

- name: ci-cert-manager-e2e-v1-9
  interval: 12h
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.9.6
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      <<: *minikube_small
      securityContext:
        privileged: true
