.minikube_small: &minikube_small
  resources:
    requests:
      cpu: 2900m
      memory: 8Gi

presubmits:
  jetstack/cert-manager:

  # bazel based cert-manager verify test
  # TODO: port to jetstack/testing images
  - name: pull-cert-manager-verify
    always_run: false
    skip_report: true
    context: pull-cert-manager-verify
    max_concurrency: 2
    agent: kubernetes
    labels:
      preset-service-account: "true"
      preset-dind-enabled: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/bazelbuild:v20180831-a4c5a2b-0.16.1
        args:
        - "--repo=github.com/$(REPO_OWNER)/$(REPO_NAME)=$(PULL_REFS)"
        - "--root=/go/src"
        - "--upload=gs://jetstack-logs/pr-logs"
        - "--job=$(JOB_NAME)"
        - "--clean"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        env:
        - name: GOPATH
          value: "/go"
        securityContext:
          privileged: true
    trigger: "(?m)^/test( all| verify),?(\\s+|$)"
    rerun_command: "/test verify"
