.minikube_small: &minikube_small
  resources:
    requests:
      cpu: 2900m
      memory: 8Gi

periodics:

- name: ci-cert-manager-e2e-v1-7
  interval: 12h
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.7.15
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      env:
      - name: DISABLE_WEBHOOK
        value: "true"
      <<: *minikube_small
      securityContext:
        privileged: true

- name: ci-cert-manager-e2e-v1-8
  interval: 12h
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.8.10
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      env:
      - name: DISABLE_WEBHOOK
        value: "true"
      <<: *minikube_small
      securityContext:
        privileged: true

- name: ci-cert-manager-e2e-v1-9
  interval: 12h
  labels:
    cert-manager-cloudflare-svc-acct: "true"
    preset-service-account: "true"
    libvirt-socket: "true"
    minikube-support: "true"
    minikube-small: "true"
  spec:
    nodeSelector:
      node-role.kubernetes.io/libvirt: ""
    tolerations:
    - effect: NoSchedule
      key: dedicated
      operator: Equal
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/minikube-in-go:v20180830-8035146-v1.9.6
      args:
      - "--repo=github.com/jetstack/cert-manager=master"
      - "--root=/go/src"
      - "--upload=gs://jetstack-logs/logs"
      - "--clean"
      <<: *minikube_small
      securityContext:
        privileged: true

- name: ci-cert-manager-e2e-v1-11
  interval: 12h
  decorate: true
  labels:
    preset-service-account: "true"
    preset-dind-enabled: "true"
    preset-bazel-remote-cache-enabled: "true"
    preset-bazel-scratch-dir: "true"
    cert-manager-cloudflare-svc-acct: "true"
  spec:
    containers:
    - image: eu.gcr.io/jetstack-build-infra-images/cert-manager-e2e:v20180918-cbbd73b-0.16.1
      args:
      - runner
      - hack/ci/run-e2e-kind.sh
      resources:
        requests:
          cpu: 2
          memory: 6Gi
      env:
      - name: KIND_IMAGE
        value: eu.gcr.io/jetstack-build-infra-images/kind:1.11.2-0
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
      - mountPath: /lib/modules
        name: modules
        readOnly: true
      - mountPath: /sys/fs/cgroup
        name: cgroup
    volumes:
    - name: modules
      hostPath:
        path: /lib/modules
        type: Directory
    - name: cgroup
      hostPath:
        path: /sys/fs/cgroup
        type: Directory
