name: alpine # Name of the image to be built

# Variants allow multiple images to be built in a single build step, with
# different build arguments for each build.
variants:
  "3.7":
    # Specify build arguments for this variant
    arguments:
      ALPINE_VERSION: "3.7"
  "3.8":
    arguments:
      ALPINE_VERSION: "3.8"

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${ALPINE_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${ALPINE_VERSION}
