presubmits:
  jetstack/preflight:

  - name: pull-preflight-unit
    cluster: gke
    agent: kubernetes
    decorate: true
    always_run: true
    max_concurrency: 8
    annotations:
      testgrid-create-test-group: 'false'
    spec:
      containers:
      - image: golang:1.13.4
        args:
        - make
        - ci-test
        resources:
          requests:
            cpu: 500m
            memory: 200Mi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
