postsubmits:
  jetstack/tarmak:
  - name: tarmak-docs-push
    branches:
    - master
    - release-0.1
    - release-0.2
    - release-0.3
    - release-0.4
    - release-0.5
    - release-0.6
    context: tarmak-docs-push
    agent: kubernetes
    decorate: true
    labels:
      preset-service-account: "true"
    spec:
      containers:
      - image: eu.gcr.io/jetstack-build-infra-images/sphinx-docs:v20180831-4ff2528
        workingDir: /go/src/github.com/jetstack/tarmak
        securityContext:
          runAsUser: 0
        command:
        - make
        - -C
        - docs
        - clean
        - multiversion_build
        - multiversion_push
        env:
        - name: DOCS_GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/docs-service-account/service-account.json
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
        volumeMounts:
        - name: docs-service
          mountPath: /etc/docs-service-account
          readOnly: true
      volumes:
      - name: docs-service
        secret:
          secretName: tarmak-docs-push-service-account
