name: bazelbuild # Name of the image to be built

# Variants allow multiple images to be built in a single build step, with
# different build arguments for each build.
variants:
  experimental:
    arguments:
      BAZEL_VERSION: "1.0.0"
      DEBIAN_VERSION: buster
      DOCKER_VERSION: 5:19.03.3~3-0~debian-buster

  "1.0.0":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: "1.0.0"
      DOCKER_VERSION: 5:18.09.4~3-0~debian-stretch

  "1.0.0rc3":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: "1.0.0"
      BAZEL_CHANNEL: "rc3"
      BAZEL_INSTALLER_FILENAME: "1.0.0rc3"

  "0.29.1":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: 0.29.1

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${BAZEL_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${BAZEL_VERSION}
