name: bazelbuild # Name of the image to be built

# Variants allow multiple images to be built in a single build step, with
# different build arguments for each build.
variants:
  experimental:
    arguments:
      BAZEL_VERSION: 0.29.1
      DEBIAN_VERSION: stretch
      DOCKER_VERSION: 5:18.09.4~3-0~debian-stretch
  "0.29.1":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: 0.29.1
  "0.28.1":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: 0.28.1
  "0.27.1":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: 0.27.1
  "0.24.1":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: 0.24.1

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${BAZEL_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${BAZEL_VERSION}
