name: bazelbuild # Name of the image to be built

# Variants allow multiple images to be built in a single build step, with
# different build arguments for each build.
variants:
  experimental:
    arguments:
      BAZEL_VERSION: "3.7.2"
      DEBIAN_VERSION: buster
      DOCKER_VERSION: 5:19.03.3~3-0~debian-buster

  "3.0.0":
    arguments:
      BAZEL_VERSION: "3.0.0"
      DEBIAN_VERSION: buster
      DOCKER_VERSION: 5:19.03.3~3-0~debian-buster

  "2.2.0":
    # Specify build arguments for this variant
    arguments:
      BAZEL_VERSION: "2.2.0"
      DEBIAN_VERSION: buster
      DOCKER_VERSION: 5:19.03.3~3-0~debian-buster

# Image names to be tagged and pushed
images:
- ${_REGISTRY}/${_NAME}:${_DATE_STAMP}-${_GIT_REF}-${BAZEL_VERSION}
- ${_REGISTRY}/${_NAME}:latest-${BAZEL_VERSION}
